# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [6]:
import tensorflow as tf
print(tf.__version__)

2.1.0


In [2]:
!pip list

Package                            Version   
---------------------------------- ----------
-                                  nsorboard 
-ensorboard                        2.1.0     
-ensorflow-estimator               2.1.0     
absl-py                            0.9.0     
alabaster                          0.7.12    
anaconda-client                    1.7.2     
anaconda-navigator                 1.9.7     
anaconda-project                   0.8.3     
arviz                              0.6.1     
asgiref                            3.2.3     
asn1crypto                         0.24.0    
astor                              0.8.1     
astroid                            2.2.5     
astropy                            3.2.1     
atomicwrites                       1.3.0     
attrs                              19.1.0    
autoimpute                         0.11.6    
Babel                              2.7.0     
backcall                           0.1.0     
backports.functools-lru-cache     

In [3]:
!pip install -U tensorflow==2.0

  Using cached https://files.pythonhosted.org/packages/54/5f/e1b2d83b808f978f51b7ce109315154da3a3d4151aa59686002681f2e109/tensorflow-2.0.0-cp37-cp37m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/76/54/99b9d5d52d5cb732f099baaaf7740403e83fe6b0cedde940fabd2b13d75a/tensorboard-2.0.2-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/fc/08/8b927337b7019c374719145d1dceba21a8bb909b93b1ad6f8fb7d22c1ca1/tensorflow_estimator-2.0.1-py2.py3-none-any.whl
  Found existing installation: tensorboard 2.1.0
    Uninstalling tensorboard-2.1.0:


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\tensorboard-2.1.0.dist-info\\entry_points.txt'
Consider using the `--user` option or check the permissions.



In [7]:
tf.__version__

'2.1.0'

In [8]:
%tensorflow_version 2.1.0

UsageError: Line magic function `%tensorflow_version` not found.


### Set random seed

In [9]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [10]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()


In [11]:
# Import `Sequential` from `keras.models` 
from keras.models import Sequential  
# Import `Dense` from `keras.layers`  
from tensorflow.keras.layers import Dense  

Using TensorFlow backend.


## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [12]:
x= iris.data

In [13]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
print(type(x))

<class 'numpy.ndarray'>


In [15]:
iris.target[[10, 25, 50]]


array([0, 0, 1])

In [16]:
y = iris.target

In [17]:
list(iris.target_names)


['setosa', 'versicolor', 'virginica']

In [20]:
list(x)

[array([5.1, 3.5, 1.4, 0.2]),
 array([4.9, 3. , 1.4, 0.2]),
 array([4.7, 3.2, 1.3, 0.2]),
 array([4.6, 3.1, 1.5, 0.2]),
 array([5. , 3.6, 1.4, 0.2]),
 array([5.4, 3.9, 1.7, 0.4]),
 array([4.6, 3.4, 1.4, 0.3]),
 array([5. , 3.4, 1.5, 0.2]),
 array([4.4, 2.9, 1.4, 0.2]),
 array([4.9, 3.1, 1.5, 0.1]),
 array([5.4, 3.7, 1.5, 0.2]),
 array([4.8, 3.4, 1.6, 0.2]),
 array([4.8, 3. , 1.4, 0.1]),
 array([4.3, 3. , 1.1, 0.1]),
 array([5.8, 4. , 1.2, 0.2]),
 array([5.7, 4.4, 1.5, 0.4]),
 array([5.4, 3.9, 1.3, 0.4]),
 array([5.1, 3.5, 1.4, 0.3]),
 array([5.7, 3.8, 1.7, 0.3]),
 array([5.1, 3.8, 1.5, 0.3]),
 array([5.4, 3.4, 1.7, 0.2]),
 array([5.1, 3.7, 1.5, 0.4]),
 array([4.6, 3.6, 1. , 0.2]),
 array([5.1, 3.3, 1.7, 0.5]),
 array([4.8, 3.4, 1.9, 0.2]),
 array([5. , 3. , 1.6, 0.2]),
 array([5. , 3.4, 1.6, 0.4]),
 array([5.2, 3.5, 1.5, 0.2]),
 array([5.2, 3.4, 1.4, 0.2]),
 array([4.7, 3.2, 1.6, 0.2]),
 array([4.8, 3.1, 1.6, 0.2]),
 array([5.4, 3.4, 1.5, 0.4]),
 array([5.2, 4.1, 1.5, 0.1]),
 array([5.

In [21]:
print(type(y))

<class 'numpy.ndarray'>


In [22]:
from tensorflow import keras

In [23]:
from tensorflow.keras import layers
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Activation,Flatten
#from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.utils import np_utils
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline
from keras.optimizers import Adam

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [24]:
# Import `train_test_split` from `sklearn.model_selection`

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


In [ ]:
# Specify the data 
#x = iris.data
# Specify the target labels and flatten the array
#y = iris.target.reshape(-1, 1) # Convert data to a single column


In [25]:
# Split the data up in train and test sets
x_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [26]:
# One Hot encode the class labels
from sklearn.preprocessing import OneHotEncoder
from keras.utils import multi_gpu_model
import tensorflow.keras.utils
from tensorflow.keras.utils import to_categorical

#encoder = OneHotEncoder(sparse=False)
#y1 = encoder.fit_transform(y)

In [27]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes = 3)

In [28]:
y_test = tf.keras.utils.to_categorical(y_test, num_classes = 3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [29]:
# Build the model

model = Sequential()

In [30]:
model

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [31]:
model.add(Dense(4, activation = 'relu', input_shape=(4,)))

In [32]:
model.add(Dense(3, activation = 'softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [33]:
model.compile(optimizer = 'sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [34]:
print('Neural Network Model Summary: ')
print(model.summary())

Neural Network Model Summary: 
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________
None


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [39]:
model.fit(x_train, y_train,validation_data=(X_test, y_test), epochs=100)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 111us/step - loss: 0.5393 - accuracy: 0.8929 - val_loss: 0.4912 - val_accuracy: 0.8158
Epoch 2/100
112/112 [==============================] - 0s 102us/step - loss: 0.5386 - accuracy: 0.8929 - val_loss: 0.4923 - val_accuracy: 0.8158
Epoch 3/100
112/112 [==============================] - 0s 63us/step - loss: 0.5383 - accuracy: 0.8929 - val_loss: 0.4924 - val_accuracy: 0.8158
Epoch 4/100
112/112 [==============================] - 0s 45us/step - loss: 0.5373 - accuracy: 0.8929 - val_loss: 0.4900 - val_accuracy: 0.8158
Epoch 5/100
112/112 [==============================] - 0s 89us/step - loss: 0.5365 - accuracy: 0.8929 - val_loss: 0.4886 - val_accuracy: 0.8421
Epoch 6/100
112/112 [==============================] - 0s 84us/step - loss: 0.5359 - accuracy: 0.8929 - val_loss: 0.4879 - val_accuracy: 0.8421
Epoch 7/100
112/112 [==============================] - 0s 100us/step - loss: 0.5357 - acc

112/112 [==============================] - 0s 118us/step - loss: 0.5027 - accuracy: 0.9107 - val_loss: 0.4669 - val_accuracy: 0.8421
Epoch 58/100
112/112 [==============================] - 0s 98us/step - loss: 0.5024 - accuracy: 0.9107 - val_loss: 0.4645 - val_accuracy: 0.8421
Epoch 59/100
112/112 [==============================] - 0s 115us/step - loss: 0.5020 - accuracy: 0.9107 - val_loss: 0.4611 - val_accuracy: 0.8421
Epoch 60/100
112/112 [==============================] - 0s 99us/step - loss: 0.5021 - accuracy: 0.9107 - val_loss: 0.4610 - val_accuracy: 0.8684
Epoch 61/100
112/112 [==============================] - 0s 93us/step - loss: 0.5006 - accuracy: 0.9196 - val_loss: 0.4616 - val_accuracy: 0.8421
Epoch 62/100
112/112 [==============================] - 0s 103us/step - loss: 0.4996 - accuracy: 0.9196 - val_loss: 0.4624 - val_accuracy: 0.8421
Epoch 63/100
112/112 [==============================] - 0s 63us/step - loss: 0.4983 - accuracy: 0.9107 - val_loss: 0.4628 - val_accuracy: 0.

## Question 10

### Make predictions
- Predict labels on one row

In [42]:
model.predict(X_test[0:1])

array([[0.07978972, 0.44980758, 0.47040278]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [43]:
y_test[0:1]

array([[0., 1., 0.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [44]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [45]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [46]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [ ]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()

In [47]:
pri_df = pd.read_csv('prices.csv')

In [48]:
pri_df.head()

date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   
2  2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000  119.739998   
3  2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000  117.440002   
4  2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996  117.330002   

      volume  
0  2163600.0  
1  2386400.0  
2  2489500.0  
3  2006300.0  
4  1408600.0

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [49]:
pri_df1 = pri_df.drop(['date', 'symbol'], axis=1)

In [50]:
pri_df1.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [51]:
pri_df1.shape

(851264, 5)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [52]:
pri_df1 = pri_df1[:1000]

In [53]:
pri_df1.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [54]:
X = pri_df1.drop('volume', axis=1)

In [55]:
y = pri_df1['volume']/1000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [56]:
X = np.array(X).astype('float32')

In [57]:
y = np.array(y).astype('float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [58]:
X = tf.math.l2_normalize(X)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [59]:
W = tf.zeros(shape=(4,1))

In [60]:
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [61]:
@tf.function
def prediction(X, W, b):
    y_predc = tf.add(tf.matmul(X, W),b)
    return y_predc

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [62]:
@tf.function
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [63]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Mathematical steps to calulate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction = prediction(x,w,b)
        current_loss = loss(y_actual, current_prediction)
#Calculate Gradients of Loss w.r.t weights and bias
    dw, db = t.gradient(current_loss,[w,b])
    
    
      #Update Weights and Bias based on gradients and learning rate to minimize loss
    w = w -  learning_rate *  dw
    b = b -  learning_rate *  db
    
    return w, b
    


## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [64]:
for i in range(100):    
    W, b = train(X, y, W, b)
    print('Current Training Loss on iteration', i, loss(y, prediction(X, W, b)).numpy())


Current Training Loss on iteration 0 236.16759
Current Training Loss on iteration 1 235.09299
Current Training Loss on iteration 2 234.06102
Current Training Loss on iteration 3 233.06998
Current Training Loss on iteration 4 232.11783
Current Training Loss on iteration 5 231.20381
Current Training Loss on iteration 6 230.32587
Current Training Loss on iteration 7 229.48265
Current Training Loss on iteration 8 228.67299
Current Training Loss on iteration 9 227.89537
Current Training Loss on iteration 10 227.14832
Current Training Loss on iteration 11 226.43114
Current Training Loss on iteration 12 225.74236
Current Training Loss on iteration 13 225.0808
Current Training Loss on iteration 14 224.44551
Current Training Loss on iteration 15 223.83502
Current Training Loss on iteration 16 223.24931
Current Training Loss on iteration 17 222.68657
Current Training Loss on iteration 18 222.14595
Current Training Loss on iteration 19 221.62688
Current Training Loss on iteration 20 221.12842
Cur

### Observe values of Weight
- Print the updated values

In [65]:
print(W)

tf.Tensor(
[[0.05478281]
 [0.05488191]
 [0.05422735]
 [0.05533117]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [66]:
print(b)

tf.Tensor([4.607657], shape=(1,), dtype=float32)
