In [1]:
import nltk
from nltk.corpus import reuters
import re, pprint
from nltk import word_tokenize
from string import punctuation
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from six import string_types
from nltk.corpus import wordnet as wn
import unicodedata
from nltk.stem import WordNetLemmatizer
import numpy as np
import pandas as pd

In [2]:
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\yogsy\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\yogsy\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [3]:
blg_df = pd.read_csv('C:/Users/yogsy/Desktop/PG Course/Project 9 - Statistical NLP Project/blogtext.csv/blogtext.csv')

In [4]:
blg_df.shape

(681284, 7)

In [5]:
blg_df.head()

id gender  age              topic      sign          date  \
0  2059027   male   15            Student       Leo   14,May,2004   
1  2059027   male   15            Student       Leo   13,May,2004   
2  2059027   male   15            Student       Leo   12,May,2004   
3  2059027   male   15            Student       Leo   12,May,2004   
4  3581210   male   33  InvestmentBanking  Aquarius  11,June,2004   

                                                text  
0             Info has been found (+/- 100 pages,...  
1             These are the team members:   Drewe...  
2             In het kader van kernfusie op aarde...  
3                   testing!!!  testing!!!            
4               Thanks to Yahoo!'s Toolbar I can ...

In [6]:
blg_df.columns

Index(['id', 'gender', 'age', 'topic', 'sign', 'date', 'text'], dtype='object')

In [7]:
blg_df.isnull().sum()

id        0
gender    0
age       0
topic     0
sign      0
date      0
text      0
dtype: int64

In [8]:
#selecting only 7500 line items

In [9]:
blg_df=blg_df[0:7500]

In [10]:
#preprocessing of data

In [11]:
# Select only alphabets
import re
blg_df.text = blg_df.text.apply(lambda x: re.sub('[^A-Za-z]+', ' ', x))

# Convert text to lowercase
blg_df.text = blg_df.text.apply(lambda x: x.lower())

# Strip unwanted spaces
blg_df.text = blg_df.text.apply(lambda x: x.strip())

# Remove stopwords
stopwords = set(stopwords.words('english'))
blg_df.text = blg_df.text.apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords]))

In [13]:
blg_df.text[10]

'ah korean language looks difficult first figure read hanguel korea surprisingly easy learn alphabet characters seems easy vocabulary starts oh backwards us sentence structure yikes luckily many options us slow witted foreigners take language course could list urllink joongang article says lot resources urllink well guy motivation jeon ji hyun latest something actually star movies cfs hear means commercial feature positive saw latest movie sunday night hard describe name english version windstruck korean version yeochinso short ne yeojachingu rul sogayhamnida like introduce girlfriend surprisingly titles make sense like website korean english looks quite good actually urllink movie shown theatres subtitles special times info urllink list many theatres seoul click urllink urllink great reason learn korean already married went foreigners well local korean national course korean take picture put urllink movie hof bar update bud mine passed urllink link giordano ad apparently aired korea n

In [15]:
### Merge the label columns
blg_df['labels'] = blg_df.apply(lambda row: [row['gender'], str(row['age']), row['topic'], row['sign']], axis=1)

In [16]:
### Select only required columns from your dataframe

blg_df = blg_df[['text','labels']]

In [17]:
blg_df.head()

text  \
0  info found pages mb pdf files wait untill team...   
1  team members drewes van der laag urllink mail ...   
2  het kader van kernfusie op aarde maak je eigen...   
3                                    testing testing   
4  thanks yahoo toolbar capture urls popups means...   

                                    labels  
0                 [male, 15, Student, Leo]  
1                 [male, 15, Student, Leo]  
2                 [male, 15, Student, Leo]  
3                 [male, 15, Student, Leo]  
4  [male, 33, InvestmentBanking, Aquarius]

In [64]:
#Creating Training and Test Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(blg_df.text.values, blg_df.labels.values, test_size=0.20, random_state=2)

In [66]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(6000,) (6000,)
(1500,) (1500,)


In [67]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1, 2),stop_words='english')

In [68]:
cv.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [69]:
len(cv.vocabulary_)

347759

In [70]:
x_train_dtm=cv.transform(X_train)

In [71]:
x_test_dtm=cv.transform(X_test)

In [72]:
x_train_dtm[0]

<1x347759 sparse matrix of type '<class 'numpy.int64'>'
	with 66 stored elements in Compressed Sparse Row format>

In [73]:
x_test_dtm[0]

<1x347759 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [74]:
print(x_train_dtm.shape)
print(x_test_dtm.shape)

(6000, 347759)
(1500, 347759)


In [19]:
#Vectorize the Features

In [15]:
#a. Create a Bag of Words using count vectorizer
# i. Use ngram_range=(1, 2)
# ii. Vectorize training and testing features

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(binary=True, ngram_range=(1, 2))
X_train_blg = vectorizer.fit_transform(X_train)
X_test_blg = vectorizer.transform(X_test)

In [22]:
vectorizer.get_feature_names()[:5]

['aa', 'aa amazing', 'aa anger', 'aa compared', 'aaa']

In [24]:
X_train_blg.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
#Create a dictionary to get the count of every label i.e. the key will be label name and value will be the total count of the label. 
#Check below image for reference

In [75]:
label_counts = dict()

for labels in blg_df.labels.values:
    for label in labels:
        if label in label_counts:
            label_counts[label] += 1
        else:
            label_counts[label] = 1

In [76]:
label_counts

{'male': 4521,
 '15': 354,
 'Student': 577,
 'Leo': 208,
 '33': 101,
 'InvestmentBanking': 70,
 'Aquarius': 351,
 'female': 2979,
 '14': 170,
 'indUnk': 2616,
 'Aries': 3722,
 '25': 268,
 'Capricorn': 88,
 '17': 914,
 'Gemini': 88,
 '23': 142,
 'Non-Profit': 47,
 'Cancer': 238,
 'Banking': 16,
 '37': 19,
 'Sagittarius': 709,
 '26': 112,
 '24': 378,
 'Scorpio': 854,
 '27': 691,
 'Education': 121,
 '45': 14,
 'Engineering': 119,
 'Libra': 425,
 'Science': 33,
 '34': 540,
 '41': 14,
 'Communications-Media': 61,
 'BusinessServices': 87,
 'Sports-Recreation': 77,
 'Virgo': 41,
 'Taurus': 709,
 'Arts': 31,
 'Pisces': 67,
 '44': 3,
 '16': 73,
 'Internet': 47,
 'Museums-Libraries': 2,
 'Accounting': 2,
 '39': 79,
 '35': 2311,
 'Technology': 2350,
 '36': 1287,
 'Law': 3,
 '46': 7,
 'Consulting': 18,
 'Automotive': 14,
 '42': 14,
 'Religion': 9,
 '13': 9,
 'Fashion': 1200}

In [77]:
#7. Transform the labels - (7.5 points) As we have noticed before, in this task each example can have multiple tags. 
#To deal with such kind of prediction, we need to transform labels in a binary form and the prediction will be a mask of 0s and 1s. 
#For this purpose, it is convenient to use MultiLabelBinarizer from sklearn
#a. Convert your train and test labels using MultiLabelBinarizer

In [78]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer(classes=sorted(label_counts.keys()))
y_train = mlb.fit_transform(y_train)
y_test = mlb.transform(y_test)

In [79]:
#Chosse as Classifier
##Use a linear classifier of your choice, wrap it up in OneVsRestClassifier to train it on every label

In [115]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(solver='lbfgs',max_iter=2000)
clf_blg = OneVsRestClassifier(clf)

In [116]:
clf_blg.fit(X_train_blg, y_train)

OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=2000,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False),
                    n_jobs=None)

In [118]:
#9. Fit the classifier, make predictions and get the accuracy (5 points)

In [119]:
#Prediction

In [124]:
predicted_labels = clf_blg.predict(X_test_blg)


In [125]:
print(predicted_labels)

[[0 0 0 ... 0 0 1]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]]


In [126]:
predicted_scores = clf_blg.decision_function(X_test_blg)

In [127]:
print(predicted_scores)

[[-10.58861184 -11.11003335  -6.42511485 ...  -4.05287783  -6.2127722
    4.05287783]
 [ -8.41253819  -5.90157883  -5.50622444 ...   0.37579402   0.25387137
   -0.37579402]
 [ -8.53681845  -4.44507618  -3.56142825 ...  -0.19758802  -0.70388324
    0.19758802]
 ...
 [ -8.28461688  -4.67824761  -2.7430466  ...  -0.52650976  -1.43440386
    0.52650976]
 [ -8.5852368   -5.17773571  -6.06795768 ...   0.33275254   1.05206107
   -0.33275254]
 [ -8.18053714  -3.52382241  -4.27240221 ...   0.94747538   0.76623379
   -0.94747538]]


In [128]:
### Inverse transform for predicted labels and test labels

In [129]:
pred_inversed = mlb.inverse_transform(predicted_labels)
y_test_inversed = mlb.inverse_transform(y_test)

In [130]:
#i. Accuracy score

In [131]:
from sklearn.metrics import accuracy_score


def print_evaluation_scores(y_val, predicted):
    print('Accuracy score: ', accuracy_score(y_val, predicted))

    

In [133]:
print('Bag-of-words')
print_evaluation_scores(y_test, predicted_labels)

Bag-of-words
Accuracy score:  0.019333333333333334


In [134]:
#ii. F1 score

In [135]:
from sklearn.metrics import f1_score
def print_evaluation_scores(y_val, predicted):
    print('F1 score: ', f1_score(y_val, predicted, average='micro'))

In [136]:
print('Bag-of-words')
print_evaluation_scores(y_test, predicted_labels)

Bag-of-words
F1 score:  0.31689901394083647


In [137]:
# iii. Average precision score
# iv. Average recall score

In [138]:
from sklearn.metrics import average_precision_score
from sklearn.metrics import recall_score

def print_evaluation_scores(y_val, predicted):
    print('Average precision score: ', average_precision_score(y_val, predicted, average='micro'))
    print('Average recall score: ', recall_score(y_val, predicted, average='micro'))

In [139]:
print('Bag-of-words')
print_evaluation_scores(y_test, predicted_labels)

Bag-of-words
Average precision score:  0.1701714741156824
Average recall score:  0.233


In [140]:
#Print true label and predicted label for any five examples (7.5 points)

In [141]:
print(y_train,predicted_labels)

[[0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]] [[0 0 0 ... 0 0 1]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]]


In [142]:
for i in range(5):
    print('Title:\t{}\nTrue labels:\t{}\nPredicted labels:\t{}\n\n'.format(
        X_test[i],
        ','.join(y_test_inversed[i]),
        ','.join(pred_inversed[i])
    ))

Title:	screwed cut pasteing part rest assured friends straight heaven bound even minutes purgatory favorite question true false pimp good thing
True labels:	36,Aries,Fashion,male
Predicted labels:	Aries,male


Title:	well kids tonight big show actually really big four bands planet smashers catch mustard plug big kids table many miss warped tour taking guys bad think taking god would rock rock rock god graces presence tonight happy girl also happy girl meet new boys right another song kids need long goodnight get kids belive thing called love darkness pretty nifty selections actually wanted catch sleep hit road know able ugh interesting esecially high hate tred ska yes know makes sense going right well put way show cleveland going guys never show fun think die pit first going go anyone wants come along tonight welcome bring powerade fine
True labels:	15,Libra,Student,female
Predicted labels:	female,indUnk


Title:	another city never thought would like los angeles never thought east coas